### ISSUE TITLE
Model path for Gemma-2b-it

### ISSUE THREAD

**Issue by revmag** [andyrdt/refusal_direction#1]
In the colab notebook demo, you have shown for qwern, can you share the same for Gemma-2b-it, want to see the results for this model.

**Comment by andyrdt** [comment]
The Colab notebook was meant to be just a brief demonstration of the technique.

The pipeline in this repo supports various model families, including Gemma. If you'd like to see results for gemma-2b-it specifically, we have its [artifacts](https://github.com/andyrdt/refusal_direction/tree/main/pipeline/runs/gemma-2b-it) available in the repository, including its JailbreakBench completions/evaluations ([baseline](https://github.com/andyrdt/refusal_direction/blob/main/pipeline/runs/gemma-2b-it/completions/jailbreakbench_baseline_evaluations.json), [directional ablation](https://github.com/andyrdt/refusal_direction/blob/main/pipeline/runs/gemma-2b-it/completions/jailbreakbench_ablation_evaluations.json)).

**Comment by YuanBoXie** [comment]
In my experiments, the refusal direction calculated in gemma2b-it and gemma7b-it seems to be very fragile. It cannot be used for jailbreaking. For example, when tested with advbench, this direction does not bring any impact. @andyrdt
