### ISSUE TITLE
Support for Phi-3-mini

### ISSUE THREAD

**Issue by razvanab** [andyrdt/refusal_direction#2]
If it is possible to support Phi-3-mini, please.
Thank you.

**Comment by andyrdt** [comment]
Hi there! Unfortunately I don't plan on actively supporting this repository (including adding support for new models), as it's meant to accompany the paper and support reproduction of the results. If you'd like to apply the method to new models, I suggest forking the repository and then making the appropriate changes there. Feel free to email me at andyrdt@gmail.com if you have questions about how to do this.
