### ISSUE TITLE
Install depreciated?

### ISSUE THREAD

**Issue by revmag** [andyrdt/refusal_direction#5]
When I run the setup ( using source setup.sh)

I get this error and the code stops: 
ERROR: Could not find a version that satisfies the requirement install==1.3.5 (from versions: none)
ERROR: No matching distribution found for install==1.3.5

It runs as usual if i remove install==1.3.5 from the requirements file.

**Comment by revmag** [comment]
It seems yes, change requirements.txt file with
pip-install==1.3.5
instead of install==1.3.5

**Comment by andyrdt** [comment]
fixed. thank you for identifying the issue and a fix!
